package com.dromedicas.dto;
// Generated 1/04/2017 11:59:12 AM by Hibernate Tools 5.1.2.Final

/**
 * Bodegas generated by hbm2java
 */
public class Bodegas implements java.io.Serializable {

	private Integer bodegaid;
	private Sucursales sucursales;
	private String codbodega;
	private String nombodega;
	private String nomcorto;
	private String tipobodega;
	private String remidestino;
	private String activa;
	private String bodespecial;

	public Bodegas() {
	}

	public Bodegas(Sucursales sucursales, String codbodega, String nombodega, String nomcorto, String tipobodega,
			String activa, String bodespecial) {
		this.sucursales = sucursales;
		this.codbodega = codbodega;
		this.nombodega = nombodega;
		this.nomcorto = nomcorto;
		this.tipobodega = tipobodega;
		this.activa = activa;
		this.bodespecial = bodespecial;
	}

	public Bodegas(Sucursales sucursales, String codbodega, String nombodega, String nomcorto, String tipobodega,
			String remidestino, String activa, String bodespecial) {
		this.sucursales = sucursales;
		this.codbodega = codbodega;
		this.nombodega = nombodega;
		this.nomcorto = nomcorto;
		this.tipobodega = tipobodega;
		this.remidestino = remidestino;
		this.activa = activa;
		this.bodespecial = bodespecial;
	}

	public Integer getBodegaid() {
		return this.bodegaid;
	}

	public void setBodegaid(Integer bodegaid) {
		this.bodegaid = bodegaid;
	}

	public Sucursales getSucursales() {
		return this.sucursales;
	}

	public void setSucursales(Sucursales sucursales) {
		this.sucursales = sucursales;
	}

	public String getCodbodega() {
		return this.codbodega;
	}

	public void setCodbodega(String codbodega) {
		this.codbodega = codbodega;
	}

	public String getNombodega() {
		return this.nombodega;
	}

	public void setNombodega(String nombodega) {
		this.nombodega = nombodega;
	}

	public String getNomcorto() {
		return this.nomcorto;
	}

	public void setNomcorto(String nomcorto) {
		this.nomcorto = nomcorto;
	}

	public String getTipobodega() {
		return this.tipobodega;
	}

	public void setTipobodega(String tipobodega) {
		this.tipobodega = tipobodega;
	}

	public String getRemidestino() {
		return this.remidestino;
	}

	public void setRemidestino(String remidestino) {
		this.remidestino = remidestino;
	}

	public String getActiva() {
		return this.activa;
	}

	public void setActiva(String activa) {
		this.activa = activa;
	}

	public String getBodespecial() {
		return this.bodespecial;
	}

	public void setBodespecial(String bodespecial) {
		this.bodespecial = bodespecial;
	}

}
