package com.dromedicas.dto;
// Generated 28/03/2017 05:43:08 PM by Hibernate Tools 5.1.2.Final

/**
 * ExistenciasId generated by hbm2java
 */
public class ExistenciasId implements java.io.Serializable {

	private int bodegaid;
	private long productoid;

	public ExistenciasId() {
	}

	public ExistenciasId(int bodegaid, long productoid) {
		this.bodegaid = bodegaid;
		this.productoid = productoid;
	}

	public int getBodegaid() {
		return this.bodegaid;
	}

	public void setBodegaid(int bodegaid) {
		this.bodegaid = bodegaid;
	}

	public long getProductoid() {
		return this.productoid;
	}

	public void setProductoid(long productoid) {
		this.productoid = productoid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExistenciasId))
			return false;
		ExistenciasId castOther = (ExistenciasId) other;

		return (this.getBodegaid() == castOther.getBodegaid()) && (this.getProductoid() == castOther.getProductoid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBodegaid();
		result = 37 * result + (int) this.getProductoid();
		return result;
	}

}
