package com.dromedicas.dto;
// Generated 28/03/2017 05:43:08 PM by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * Existencias generated by hbm2java
 */
public class Existencias implements java.io.Serializable {

	private ExistenciasId id;
	private double cantidad;
	private Date ultcambio;

	public Existencias() {
	}

	public Existencias(ExistenciasId id, double cantidad, Date ultcambio) {
		this.id = id;
		this.cantidad = cantidad;
		this.ultcambio = ultcambio;
	}

	public ExistenciasId getId() {
		return this.id;
	}

	public void setId(ExistenciasId id) {
		this.id = id;
	}

	public double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(double cantidad) {
		this.cantidad = cantidad;
	}

	public Date getUltcambio() {
		return this.ultcambio;
	}

	public void setUltcambio(Date ultcambio) {
		this.ultcambio = ultcambio;
	}

}
