package com.dromedicas.dto;
// Generated 5/04/2017 03:19:03 PM by Hibernate Tools 5.1.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Incidente generated by hbm2java
 */
public class Incidente implements java.io.Serializable {

	private Integer idincidente;
	private Tipoincidente tipoincidente;
	private String cliente;
	private Date ocurrencia;
	private Date cierre;
	private Set notificacions = new HashSet(0);

	public Incidente() {
	}

	public Incidente(Tipoincidente tipoincidente, String cliente) {
		this.tipoincidente = tipoincidente;
		this.cliente = cliente;
	}

	public Incidente(Tipoincidente tipoincidente, String cliente, Date ocurrencia, Date cierre, Set notificacions) {
		this.tipoincidente = tipoincidente;
		this.cliente = cliente;
		this.ocurrencia = ocurrencia;
		this.cierre = cierre;
		this.notificacions = notificacions;
	}

	public Integer getIdincidente() {
		return this.idincidente;
	}

	public void setIdincidente(Integer idincidente) {
		this.idincidente = idincidente;
	}

	public Tipoincidente getTipoincidente() {
		return this.tipoincidente;
	}

	public void setTipoincidente(Tipoincidente tipoincidente) {
		this.tipoincidente = tipoincidente;
	}

	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public Date getOcurrencia() {
		return this.ocurrencia;
	}

	public void setOcurrencia(Date ocurrencia) {
		this.ocurrencia = ocurrencia;
	}

	public Date getCierre() {
		return this.cierre;
	}

	public void setCierre(Date cierre) {
		this.cierre = cierre;
	}

	public Set getNotificacions() {
		return this.notificacions;
	}

	public void setNotificacions(Set notificacions) {
		this.notificacions = notificacions;
	}

	@Override
	public String toString() {
		return "Incidente [idincidente=" + idincidente + ", tipoincidente=" + tipoincidente + ", cliente=" + cliente
				+ ", ocurrencia=" + ocurrencia + ", cierre=" + cierre + ", notificacions=" + notificacions + "]";
	}
	
	

}
