package com.dromedicas.dto;
// Generated 28/03/2017 05:43:08 PM by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales implements java.io.Serializable {

	private Integer sucursalid;
	private String version;
	private String codigo;
	private String descripcion;
	private String zona;
	private String direccion;
	private Long ciudadcodigo;
	private String telefono;
	private String telefono2;
	private String celular;
	private String email;
	private Double totventas;
	private String diaoperativo;
	private String ultcierre;
	private String ultrecepcion;
	private String utlrecepauto;
	private Date ultrecekardex;
	private String activa;
	private String esdrogueria;
	private String rutaweb;
	private String lispre1;
	private String lispre2;
	private String lispre3;
	private String lispre4;
	private String lispre5;
	private Date dctodesde;
	private Date dctohasta;
	private double porcen;
	private String horacierre;
	private String direccionip;
	private Date horaperturagen;
	private Date horacierregen;
	private Date horaperturaes;
	private Date horacierrees;
	private String es24horas;
	private String latitud;
	private String longitud;
	private String direccion2;
	private String pervenregu;

	public Sucursales() {
	}

	public Sucursales(String codigo, String descripcion, String zona, String direccion, String telefono, String email,
			String diaoperativo, String ultcierre, Date ultrecekardex, String activa, String esdrogueria,
			Date dctodesde, Date dctohasta, double porcen, String horacierre) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.zona = zona;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.diaoperativo = diaoperativo;
		this.ultcierre = ultcierre;
		this.ultrecekardex = ultrecekardex;
		this.activa = activa;
		this.esdrogueria = esdrogueria;
		this.dctodesde = dctodesde;
		this.dctohasta = dctohasta;
		this.porcen = porcen;
		this.horacierre = horacierre;
	}

	public Sucursales(String codigo, String descripcion, String zona, String direccion, Long ciudadcodigo,
			String telefono, String telefono2, String celular, String email, Double totventas, String diaoperativo,
			String ultcierre, String ultrecepcion, String utlrecepauto, Date ultrecekardex, String activa,
			String esdrogueria, String rutaweb, String lispre1, String lispre2, String lispre3, String lispre4,
			String lispre5, Date dctodesde, Date dctohasta, double porcen, String horacierre, String direccionip,
			Date horaperturagen, Date horacierregen, Date horaperturaes, Date horacierrees, String es24horas,
			String latitud, String longitud, String direccion2, String pervenregu) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.zona = zona;
		this.direccion = direccion;
		this.ciudadcodigo = ciudadcodigo;
		this.telefono = telefono;
		this.telefono2 = telefono2;
		this.celular = celular;
		this.email = email;
		this.totventas = totventas;
		this.diaoperativo = diaoperativo;
		this.ultcierre = ultcierre;
		this.ultrecepcion = ultrecepcion;
		this.utlrecepauto = utlrecepauto;
		this.ultrecekardex = ultrecekardex;
		this.activa = activa;
		this.esdrogueria = esdrogueria;
		this.rutaweb = rutaweb;
		this.lispre1 = lispre1;
		this.lispre2 = lispre2;
		this.lispre3 = lispre3;
		this.lispre4 = lispre4;
		this.lispre5 = lispre5;
		this.dctodesde = dctodesde;
		this.dctohasta = dctohasta;
		this.porcen = porcen;
		this.horacierre = horacierre;
		this.direccionip = direccionip;
		this.horaperturagen = horaperturagen;
		this.horacierregen = horacierregen;
		this.horaperturaes = horaperturaes;
		this.horacierrees = horacierrees;
		this.es24horas = es24horas;
		this.latitud = latitud;
		this.longitud = longitud;
		this.direccion2 = direccion2;
		this.pervenregu = pervenregu;
	}

	public Integer getSucursalid() {
		return this.sucursalid;
	}

	public void setSucursalid(Integer sucursalid) {
		this.sucursalid = sucursalid;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getZona() {
		return this.zona;
	}

	public void setZona(String zona) {
		this.zona = zona;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Long getCiudadcodigo() {
		return this.ciudadcodigo;
	}

	public void setCiudadcodigo(Long ciudadcodigo) {
		this.ciudadcodigo = ciudadcodigo;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Double getTotventas() {
		return this.totventas;
	}

	public void setTotventas(Double totventas) {
		this.totventas = totventas;
	}

	public String getDiaoperativo() {
		return this.diaoperativo;
	}

	public void setDiaoperativo(String diaoperativo) {
		this.diaoperativo = diaoperativo;
	}

	public String getUltcierre() {
		return this.ultcierre;
	}

	public void setUltcierre(String ultcierre) {
		this.ultcierre = ultcierre;
	}

	public String getUltrecepcion() {
		return this.ultrecepcion;
	}

	public void setUltrecepcion(String ultrecepcion) {
		this.ultrecepcion = ultrecepcion;
	}

	public String getUtlrecepauto() {
		return this.utlrecepauto;
	}

	public void setUtlrecepauto(String utlrecepauto) {
		this.utlrecepauto = utlrecepauto;
	}

	public Date getUltrecekardex() {
		return this.ultrecekardex;
	}

	public void setUltrecekardex(Date ultrecekardex) {
		this.ultrecekardex = ultrecekardex;
	}

	public String getActiva() {
		return this.activa;
	}

	public void setActiva(String activa) {
		this.activa = activa;
	}

	public String getEsdrogueria() {
		return this.esdrogueria;
	}

	public void setEsdrogueria(String esdrogueria) {
		this.esdrogueria = esdrogueria;
	}

	public String getRutaweb() {
		return this.rutaweb;
	}

	public void setRutaweb(String rutaweb) {
		this.rutaweb = rutaweb;
	}

	public String getLispre1() {
		return this.lispre1;
	}

	public void setLispre1(String lispre1) {
		this.lispre1 = lispre1;
	}

	public String getLispre2() {
		return this.lispre2;
	}

	public void setLispre2(String lispre2) {
		this.lispre2 = lispre2;
	}

	public String getLispre3() {
		return this.lispre3;
	}

	public void setLispre3(String lispre3) {
		this.lispre3 = lispre3;
	}

	public String getLispre4() {
		return this.lispre4;
	}

	public void setLispre4(String lispre4) {
		this.lispre4 = lispre4;
	}

	public String getLispre5() {
		return this.lispre5;
	}

	public void setLispre5(String lispre5) {
		this.lispre5 = lispre5;
	}

	public Date getDctodesde() {
		return this.dctodesde;
	}

	public void setDctodesde(Date dctodesde) {
		this.dctodesde = dctodesde;
	}

	public Date getDctohasta() {
		return this.dctohasta;
	}

	public void setDctohasta(Date dctohasta) {
		this.dctohasta = dctohasta;
	}

	public double getPorcen() {
		return this.porcen;
	}

	public void setPorcen(double porcen) {
		this.porcen = porcen;
	}

	public String getHoracierre() {
		return this.horacierre;
	}

	public void setHoracierre(String horacierre) {
		this.horacierre = horacierre;
	}

	public String getDireccionip() {
		return this.direccionip;
	}

	public void setDireccionip(String direccionip) {
		this.direccionip = direccionip;
	}

	public Date getHoraperturagen() {
		return this.horaperturagen;
	}

	public void setHoraperturagen(Date horaperturagen) {
		this.horaperturagen = horaperturagen;
	}

	public Date getHoracierregen() {
		return this.horacierregen;
	}

	public void setHoracierregen(Date horacierregen) {
		this.horacierregen = horacierregen;
	}

	public Date getHoraperturaes() {
		return this.horaperturaes;
	}

	public void setHoraperturaes(Date horaperturaes) {
		this.horaperturaes = horaperturaes;
	}

	public Date getHoracierrees() {
		return this.horacierrees;
	}

	public void setHoracierrees(Date horacierrees) {
		this.horacierrees = horacierrees;
	}

	public String getEs24horas() {
		return this.es24horas;
	}

	public void setEs24horas(String es24horas) {
		this.es24horas = es24horas;
	}

	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	public String getDireccion2() {
		return this.direccion2;
	}

	public void setDireccion2(String direccion2) {
		this.direccion2 = direccion2;
	}

	public String getPervenregu() {
		return this.pervenregu;
	}

	public void setPervenregu(String pervenregu) {
		this.pervenregu = pervenregu;
	}

}
