package com.dromedicas.dto;
// Generated 5/04/2017 03:19:03 PM by Hibernate Tools 5.1.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipoincidente generated by hbm2java
 */
public class Tipoincidente implements java.io.Serializable {

	private Integer idtipoincidente;
	private String nombreincidente;
	private String descripcion;
	private double horasintervalo;
	private Set incidentes = new HashSet(0);

	public Tipoincidente() {
	}

	public Tipoincidente(String nombreincidente, double horasintervalo) {
		this.nombreincidente = nombreincidente;
		this.horasintervalo = horasintervalo;
	}

	public Tipoincidente(String nombreincidente, String descripcion, double horasintervalo, Set incidentes) {
		this.nombreincidente = nombreincidente;
		this.descripcion = descripcion;
		this.horasintervalo = horasintervalo;
		this.incidentes = incidentes;
	}

	public Integer getIdtipoincidente() {
		return this.idtipoincidente;
	}

	public void setIdtipoincidente(Integer idtipoincidente) {
		this.idtipoincidente = idtipoincidente;
	}

	public String getNombreincidente() {
		return this.nombreincidente;
	}

	public void setNombreincidente(String nombreincidente) {
		this.nombreincidente = nombreincidente;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getHorasintervalo() {
		return this.horasintervalo;
	}

	public void setHorasintervalo(double horasintervalo) {
		this.horasintervalo = horasintervalo;
	}

	public Set getIncidentes() {
		return this.incidentes;
	}

	public void setIncidentes(Set incidentes) {
		this.incidentes = incidentes;
	}

}
